INSERT INTO skill VALUES ( 1, 'Athletics', 'Your Strength (Athletics) check covers difficult situations you encounter while climbing, jumping, or swimming. Examples include the following activities:<br/>* You attempt to climb a sheer or slippery cliff, avoid hazards while scaling a wall, or cling to a surface while something is trying to knock you off.<br/>* You try to jump an unusually long distance or pull off a stunt midjump.<br/>* You struggle to swim or stay afloat in treacherous currents, storm-tossed waves, or areas of thick seaweed. Or another creature tries to push or pull you underwater or otherwise interfere with your swimming.', 0, 0 );
INSERT INTO skill VALUES ( 2, 'Acrobatics', 'Your Dexterity (Acrobatics) check covers your attempt to stay on your feet in a tricky situation, such as when you’re trying to run across a sheet of ice, balance on a tightrope, or stay upright on a rocking ship’s deck. The GM might also call for a Dexterity (Acrobatics) check to see if you can perform acrobatic stunts, including dives, rolls, somersaults, and flips.', 1, 0 );
INSERT INTO skill VALUES ( 3, 'Sleight of Hand', 'Whenever you attempt an act of legerdemain or manual trickery, such as planting something on someone else or concealing an object on your person, make a Dexterity (Sleight of Hand) check. The GM might also call for a Dexterity (Sleight of Hand) check to determine whether you can lift a coin purse off another person or slip something out of another person’s pocket.', 1, 0 );
INSERT INTO skill VALUES ( 4, 'Stealth', 'Make a Dexterity (Stealth) check when you attempt to conceal yourself from enemies, slink past guards, slip away without being noticed, or sneak up on someone without being seen or heard.', 1, 0 );
INSERT INTO skill VALUES ( 5, 'Arcana', 'Your Intelligence (Arcana) check measures your ability to recall lore about spells, magic items, eldritch symbols, magical traditions, the planes of existence, and the inhabitants of those planes.', 3, 0 );
INSERT INTO skill VALUES ( 6, 'History', 'Your Intelligence (History) check measures your ability to recall lore about historical events, legendary people, ancient kingdoms, past disputes, recent wars, and lost civilizations.', 3, 0 );
INSERT INTO skill VALUES ( 7, 'Investigation', 'When you look around for clues and make deductions based on those clues, you make an Intelligence (Investigation) check. You might deduce the location of a hidden object, discern from the appearance of a wound what kind of weapon dealt it, or determine the weakest point in a tunnel that could cause it to collapse. Poring through ancient scrolls in search of a hidden fragment of knowledge might also call for an Intelligence (Investigation) check.', 3, 0 );
INSERT INTO skill VALUES ( 8, 'Nature', 'Your Intelligence (Nature) check measures your ability to recall lore about terrain, plants and animals, the weather, and natural cycles.', 3, 0 );
INSERT INTO skill VALUES ( 9, 'Religion', 'Your Intelligence (Religion) check measures your ability to recall lore about deities, rites and prayers, religious hierarchies, holy symbols, and the practices of secret cults.', 3, 0 );
INSERT INTO skill VALUES ( 10, 'Animal Handling', 'When there is any question whether you can calm down a domesticated animal, keep a mount from getting spooked, or intuit an animal’s intentions, the GM might call for a Wisdom (Animal Handling) check. You also make a Wisdom (Animal Handling) check to control your mount when you attempt a risky maneuver.', 4, 0 );
INSERT INTO skill VALUES ( 11, 'Insight', 'Your Wisdom (Insight) check decides whether you can determine the true intentions of a creature, such as when searching out a lie or predicting someone’s next move. Doing so involves gleaning clues from body language, speech habits, and changes in mannerisms.', 4, 0 );
INSERT INTO skill VALUES ( 12, 'Medicine', 'A Wisdom (Medicine) check lets you try to stabilize a dying companion or diagnose an illness.', 4, 0 );
INSERT INTO skill VALUES ( 13, 'Perception', 'Your Wisdom (Perception) check lets you spot, hear, or otherwise detect the presence of something. It measures your general awareness of your surroundings and the keenness of your senses. For example, you might try to hear a conversation through a closed door, eavesdrop under an open window, or hear monsters moving stealthily in the forest. Or you might try to spot things that are obscured or easy to miss, whether they are orcs lying in ambush on a road, thugs hiding in the shadows of an alley, or candlelight under a closed secret door.', 4, 0 );
INSERT INTO skill VALUES ( 14, 'Survival', 'The GM might ask you to make a Wisdom (Survival) check to follow tracks, hunt wild game, guide your group through frozen wastelands, identify signs that owlbears live nearby, predict the weather, or avoid quicksand and other natural hazards.', 4, 0 );
INSERT INTO skill VALUES ( 15, 'Deception', 'Your Charisma (Deception) check determines whether you can convincingly hide the truth, either verbally or through your actions. This deception can encompass everything from misleading others through ambiguity to telling outright lies. Typical situations include trying to fast- talk a guard, con a merchant, earn money through gambling, pass yourself off in a disguise, dull someone’s suspicions with false assurances, or maintain a straight face while telling a blatant lie.', 5, 0 );
INSERT INTO skill VALUES ( 16, 'Intimidation', 'When you attempt to influence someone through overt threats, hostile actions, and physical violence, the GM might ask you to make a Charisma (Intimidation) check. Examples include trying to pry information out of a prisoner, convincing street thugs to back down from a confrontation, or using the edge of a broken bottle to convince a sneering vizier to reconsider a decision.', 5, 0 );
INSERT INTO skill VALUES ( 17, 'Performance', 'Your Charisma (Performance) check determines how well you can delight an audience with music, dance, acting, storytelling, or some other form of entertainment.', 5, 0 );
INSERT INTO skill VALUES ( 18, 'Persuasion', 'When you attempt to influence someone or a group of people with tact, social graces, or good nature, the GM might ask you to make a Charisma (Persuasion) check. Typically, you use persuasion when acting in good faith, to foster friendships, make cordial requests, or exhibit proper etiquette. Examples of persuading others include convincing a chamberlain to let your party see the king, negotiating peace between warring tribes, or inspiring a crowd of townsfolk.', 5, 0 );


INSERT INTO class_skill VALUES (1, 1);
INSERT INTO class_skill VALUES (2, 1);
INSERT INTO class_skill VALUES (5, 1);
INSERT INTO class_skill VALUES (6, 1);
INSERT INTO class_skill VALUES (7, 1);
INSERT INTO class_skill VALUES (8, 1);
INSERT INTO class_skill VALUES (9, 1);
INSERT INTO class_skill VALUES (2, 2);
INSERT INTO class_skill VALUES (5, 2);
INSERT INTO class_skill VALUES (6, 2);
INSERT INTO class_skill VALUES (9, 2);
INSERT INTO class_skill VALUES (2, 3);
INSERT INTO class_skill VALUES (9, 3);
INSERT INTO class_skill VALUES (2, 4);
INSERT INTO class_skill VALUES (6, 4);
INSERT INTO class_skill VALUES (8, 4);
INSERT INTO class_skill VALUES (9, 4);
INSERT INTO class_skill VALUES (2, 5);
INSERT INTO class_skill VALUES (4, 5);
INSERT INTO class_skill VALUES (10, 5);
INSERT INTO class_skill VALUES (11, 5);
INSERT INTO class_skill VALUES (12, 5);
INSERT INTO class_skill VALUES (2, 6);
INSERT INTO class_skill VALUES (3, 6);
INSERT INTO class_skill VALUES (5, 6);
INSERT INTO class_skill VALUES (6, 6);
INSERT INTO class_skill VALUES (11, 6);
INSERT INTO class_skill VALUES (12, 6);
INSERT INTO class_skill VALUES (2, 7);
INSERT INTO class_skill VALUES (8, 7);
INSERT INTO class_skill VALUES (9, 7);
INSERT INTO class_skill VALUES (11, 7);
INSERT INTO class_skill VALUES (12, 7);
INSERT INTO class_skill VALUES (1, 8);
INSERT INTO class_skill VALUES (2, 8);
INSERT INTO class_skill VALUES (4, 8);
INSERT INTO class_skill VALUES (8, 8);
INSERT INTO class_skill VALUES (11, 8);
INSERT INTO class_skill VALUES (2, 9);
INSERT INTO class_skill VALUES (3, 9);
INSERT INTO class_skill VALUES (4, 9);
INSERT INTO class_skill VALUES (6, 9);
INSERT INTO class_skill VALUES (7, 9);
INSERT INTO class_skill VALUES (10, 9);
INSERT INTO class_skill VALUES (11, 9);
INSERT INTO class_skill VALUES (12, 9);
INSERT INTO class_skill VALUES (1, 10);
INSERT INTO class_skill VALUES (2, 10);
INSERT INTO class_skill VALUES (4, 10);
INSERT INTO class_skill VALUES (5, 10);
INSERT INTO class_skill VALUES (8, 10);
INSERT INTO class_skill VALUES (2, 11);
INSERT INTO class_skill VALUES (3, 11);
INSERT INTO class_skill VALUES (4, 11);
INSERT INTO class_skill VALUES (5, 11);
INSERT INTO class_skill VALUES (6, 11);
INSERT INTO class_skill VALUES (7, 11);
INSERT INTO class_skill VALUES (8, 11);
INSERT INTO class_skill VALUES (9, 11);
INSERT INTO class_skill VALUES (10, 11);
INSERT INTO class_skill VALUES (12, 11);
INSERT INTO class_skill VALUES (2, 12);
INSERT INTO class_skill VALUES (3, 12);
INSERT INTO class_skill VALUES (4, 12);
INSERT INTO class_skill VALUES (7, 12);
INSERT INTO class_skill VALUES (12, 12);
INSERT INTO class_skill VALUES (1, 13);
INSERT INTO class_skill VALUES (2, 13);
INSERT INTO class_skill VALUES (4, 13);
INSERT INTO class_skill VALUES (5, 13);
INSERT INTO class_skill VALUES (8, 13);
INSERT INTO class_skill VALUES (9, 13);
INSERT INTO class_skill VALUES (1, 14);
INSERT INTO class_skill VALUES (2, 14);
INSERT INTO class_skill VALUES (4, 14);
INSERT INTO class_skill VALUES (5, 14);
INSERT INTO class_skill VALUES (8, 14);
INSERT INTO class_skill VALUES (2, 15);
INSERT INTO class_skill VALUES (9, 15);
INSERT INTO class_skill VALUES (10, 15);
INSERT INTO class_skill VALUES (11, 15);
INSERT INTO class_skill VALUES (1, 16);
INSERT INTO class_skill VALUES (2, 16);
INSERT INTO class_skill VALUES (5, 16);
INSERT INTO class_skill VALUES (7, 16);
INSERT INTO class_skill VALUES (9, 16);
INSERT INTO class_skill VALUES (10, 16);
INSERT INTO class_skill VALUES (11, 16);
INSERT INTO class_skill VALUES (2, 17);
INSERT INTO class_skill VALUES (9, 17);
INSERT INTO class_skill VALUES (2, 18);
INSERT INTO class_skill VALUES (3, 18);
INSERT INTO class_skill VALUES (7, 18);
INSERT INTO class_skill VALUES (9, 18);
INSERT INTO class_skill VALUES (10, 18);
