INSERT INTO race VALUES (11, 'Aasimar', 4, 30, -1 );
INSERT INTO race VALUES (12, 'Catfolk', 4, 30, -1 );
INSERT INTO race VALUES (13, 'Changeling', 4, 30, -1 );
INSERT INTO race VALUES (14, 'Dhampir', 4, 30, -1 );
INSERT INTO race VALUES (15, 'Drow', 4, 30, -1 );
INSERT INTO race VALUES (16, 'Duergar', 4, 20, -1 );
INSERT INTO race VALUES (17, 'Fetchling', 4, 30, -1 );
INSERT INTO race VALUES (18, 'Gillman', 4, 30, -1 );
INSERT INTO race VALUES (19, 'Goblin', 3, 30, -1 );
INSERT INTO race VALUES (20, 'Grippli', 3, 30, -1 );
INSERT INTO race VALUES (21, 'Hobgoblin', 4, 30, -1 );
INSERT INTO race VALUES (22, 'Ifrit', 4, 30, -1 );
INSERT INTO race VALUES (23, 'Kitsune', 4, 30, -1 );
INSERT INTO race VALUES (24, 'Kobold', 3, 30, -1 );
INSERT INTO race VALUES (25, 'Merfolk', 4, 50, -1 );
INSERT INTO race VALUES (26, 'Nagaji', 4, 30, -1 );
INSERT INTO race VALUES (27, 'Orc', 4, 30, -1 );
INSERT INTO race VALUES (28, 'Oread', 4, 20, -1 );
INSERT INTO race VALUES (29, 'Ratfolk', 4, 20, -1 );
INSERT INTO race VALUES (30, 'Samsaran', 4, 30, -1 );
INSERT INTO race VALUES (31, 'Strix', 4, 60, -1 );
INSERT INTO race VALUES (32, 'Suli', 4, 30, -1 );
INSERT INTO race VALUES (33, 'Svirfneblin', 3, 20, -1 );
INSERT INTO race VALUES (34, 'Sylph', 4, 30, -1 );
INSERT INTO race VALUES (35, 'Tengu', 4, 30, -1 );
INSERT INTO race VALUES (36, 'Tiefling', 4, 30, -1 );
INSERT INTO race VALUES (37, 'Undine', 4, 30, -1 );
INSERT INTO race VALUES (38, 'Vanara', 4, 30, -1 );
INSERT INTO race VALUES (39, 'Vishkanya', 4, 30, -1 );
INSERT INTO race VALUES (40, 'Wayang', 4, 20, -1 );


INSERT INTO ability VALUES ( 1084, '+2 Wisdom, +2 Charisma', 'Aasimars are insightful, confident, and personable. Aasimars of specific bloodlines (see below) gain different ability score modifiers as indicated.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1085, 'Native Outsider', 'Are an outsiders with the native subtype.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1086, 'Skilled Diplomacy & Perception', 'Aasimars have a +2 racial bonus on Diplomacy and Perception checks. Aasimars of specific bloodlines (see below) gain a +2 bonus on different skill checks as indicated.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1087, 'Spell-Like Ability', 'Aasimars can use daylight once per day as a spell-like ability (with a caster level equal to the aasimar''s character level). Aasimars of specific bloodlines (see below) gain other spell-like abilities in place of daylight.', 2, 'Ability' );
INSERT INTO ability VALUES ( 1088, 'Celestial Resistance', 'Aasimars have acid resistance 5, cold resistance 5, and electricity resistance 5.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1089, '+2 Dexterity, +2 Charisma, -2 Wisdom', 'Catfolk are sociable and agile, but often lack common sense', 0, 'Ability' );
INSERT INTO ability VALUES ( 1090, 'Cat''s Luck', 'Once per day when a catfolk attempts a Reflex saving throw, he can roll the saving throw twice and take the better result. He must decide to use this ability before the saving throw is attempted.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1091, 'Natural Hunter', 'Catfolk receive a +2 racial bonus on Perception, Stealth, and Survival checks.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1092, 'Sprinter', 'Catfolk gain a 10-foot racial bonus to their speed when using the charge, run, or withdraw actions.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1093, 'Catfolk', 'Catfolk are humanoids with the catfolk subtype.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1094, '+2 Wisdom, +2 Charisma, -2 Constitution', 'Changelings are frail, but are clever and comely.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1095, 'Changeling', 'Changelings are humanoids with the changeling subtype.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1096, 'Hag Racial Trait', 'Each changeling inherits one of the following racial traits, depending on her mother''s hag type. (As outsiders, night hags produce half-fiend children, not changelings.)', 0, 'Ability' );
INSERT INTO ability VALUES ( 1097, 'Crawling Skin (Blood Hag)', 'The changeling gains a +2 bonus on Disguise checks made to look like specific individuals.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1098, 'Dead Eyes (Mute Hag)', 'One of the changeling''s eyes is a solid, dead black (with no whites even at its edges), this gives her a +2 bonus on all saves against gaze attacks and visual illusions.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1099, 'Frostlaced Flesh (Winter Hag)', 'The changeling leaves no tracks in snow, and gains a +2 racial bonus on all saves versus cold effects.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1100, 'Green Widow (Green Hag)', 'The changeling gains a +2 racial bonus on Bluff checks against creatures that are sexually attracted to her.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1101, 'Hulking Changeling (Annis Hag)', 'The changeling gains a +1 racial bonus on melee damage rolls.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1102, 'Into the Wind (Storm Hag)', 'The changeling gains a +1 racial bonus on ranged damage rolls.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1103, 'Sea Lungs (Sea Hag)', 'The changeling can hold her breath for a number of rounds equal to 3 x her Constitution before she risks drowning.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1104, 'Claws', 'Claws granting two claw attacks (1d4 points of damage each).', 0, 'Ability' );
INSERT INTO ability VALUES ( 1105, 'Natural Armor', 'A +1 natural armor bonus.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1106, '+2 Dexterity, +2 Charisma, -2 Constitution', 'Dhampirs are fast and seductive, but their mortal vigor is impeded. Dhampirs of specific heritages (see below) gain different ability score modifiers as indicated.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1107, 'Senses', 'Dhampirs get low-light vision and darkvision with a range of 60 feet.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1108, 'Manipulative', 'Dhampirs gain a +2 racial bonus on Bluff and Perception checks. Dhampirs of specific heritages (see below) gain a +2 bonus on different skill checks as indicated.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1109, 'Undead Resistance', 'Dhampirs gain a +2 racial bonus on saving throws against disease and mind-affecting effects.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1110, 'Light Sensitivity', 'Dhampirs are dazzled in areas of bright sunlight or within the radius of a daylight spell. Dhampirs of specific heritages (see below) gain different weaknesses.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1111, 'Negative Energy Affinity', 'Though they''''re living creatures, dhampirs react to positive and negative energy as if they were undead, positive energy harms them, and negative energy heals them.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1112, 'Spell-Like Ability', 'A dhampir can use detect undead three times per day as a spell-like ability (with a caster level equal to the dhampir''s character level). Dhampirs of specific heritages (see below) gain other spell-like abilities in place of detect undead.', 2, 'Ability' );
INSERT INTO ability VALUES ( 1113, 'Resist Level Drain', 'A dhampir takes no penalties from energy drain effects, though he can still be killed if he accrues more negative levels then he has Hit Dice. After 24 hours, any negative levels a dhampir takes are removed without the need for an additional saving throw.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1114, '+2 Dexterity, +2 Charisma, -2 Constitution', 'Drow are nimble and manipulative.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1115, 'Drow Immunities', 'Drow are immune to magic sleep effects and gain a +2 racial bonus on saving throws against enchantment spells and effects.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1116, 'Poison Use', 'Are skilled in the use of poison and never risk accidentally poisoning themselves.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1117, 'Spell Resistance', 'A drow possesses an amount of spell resistance equal to 6 + her character level.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1118, 'Spell-Like Abilities', 'A drow can cast dancing lights, darkness, and faerie fire, each once per day, using her total character level as her caster level.', 2, 'Ability' );
INSERT INTO ability VALUES ( 1119, 'Light Blindness', 'Abrupt exposure to bright light blinds drow for 1 round, on subsequent rounds, they are dazzled as long as they remain in the affected area.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1120, 'Weapon Familiarity', 'Drow are proficient with the hand crossbow, rapier, and short sword.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1121, 'Superior Darkvision', 'Darksight up to 120 feet', 0, 'Ability' );
INSERT INTO ability VALUES ( 1122, '+2 Constitution, +2 Wisdom, -4 Charisma', 'Duergar are hearty and observant, but also belligerent.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1123, 'Duergar Immunities', 'Duergar are immune to paralysis, phantasms, and poison. They gain a +2 racial bonus on saves against spells and spell-like abilities.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1124, 'Spell-Like Abilities', 'A duergar can use enlarge person and invisibility each once per day, using her character level as her caster level and affecting itself only.', 2, 'Ability' );
INSERT INTO ability VALUES ( 1125, 'Light Sensitivity', 'Are dazzled in areas of bright light.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1126, '+2 Dexterity, +2 Charisma, -2 Wisdom', 'Fetchlings are quick and forceful, but often strange and easily distracted by errant thoughts.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1127, 'Skilled Knowledge & Stealth ', 'Fetchlings have a +2 racial bonus on Knowledge (planes) and Stealth checks.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1128, 'Shadow Blending', 'Attacks against a fetchling in dim light have a 50% miss chance instead of the normal 20% miss chance. This ability does not grant total concealment, it just increases the miss chance.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1129, 'Shadowy Resistance', 'Fetchlings have cold resistance 5 and electricity resistance 5.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1130, 'Spell-Like Abilities', 'A fetchling can use disguise self once per day as a spell-like ability. He can assume the form of any humanoid creature using this spell-like ability. When a fetchling reaches character 9th level in any combination of classes, he gains shadow walk (self only) as a spell-like ability usable once per day, and at 13th level, he gains plane shift (self only, to the Shadow Plane or the Material Plane only) usable once per day. A fetchling''s caster level for these abilities is equal to his character level.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1131, '+2 Constitution, +2 Charisma, -2 Wisdom', 'Gillmen are vigorous and beautiful, but their domination by the aboleths has made them weak-willed.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1132, 'Aquatic', 'Gillmen are humanoids with the aquatic subtype. ', 0, 'Ability' );
INSERT INTO ability VALUES ( 1133, 'Normal Speed', 'Gillmen have a base speed of 30 feet on land. As aquatic creatures, they also have a swim speed of 30 feet, can move in water without making Swim checks, and always treat Swim as a class skill.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1134, 'Amphibious', 'Gillmen have the aquatic subtype, but can breathe both water and air.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1135, 'Enchantment Resistance', 'Gillmen gain a +2 racial saving throw bonus against non-aboleth enchantment spells and effects, but take a -2 penalty on such saving throws against aboleth sources.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1136, 'Water Dependent', 'A gillman''s body requires constant submersion in fresh or salt water. Gillmen who spend more than 1 day without fully submerging themselves in water risk internal organ failure, painful cracking of the skin, and death within 4d6 hours.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1137, '+4 Dexterity, -2 Strength, -2 Charisma', 'Goblins are fast but weak, and they''re unpleasant to be around.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1138, 'Goblinoid', 'Goblins are humanoids with the goblinoid subtype.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1139, 'Small', 'Are Small and gain a +1 size bonus to their AC, a +1 size bonus on attack rolls, a -1 penalty on combat maneuver checks and to their Combat Maneuver Defense, and a +4 size bonus on Stealth checks.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1140, 'Normal Speed', 'Goblins are fast for their size, and have a base speed of 30 feet.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1141, 'Skilled', '+4 racial bonus on Ride and Stealth checks.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1142, '+2 Dexterity, +2 Wisdom, -2 Strength', 'Gripplis are nimble and alert, but spindly.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1143, 'Grippli', 'Gripplis are humanoids with the grippli subtype.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1144, 'Normal Speed', 'Gripplis have a base speed of 30 feet.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1145, 'Natural Climber', 'Gripplis have a climb speed of 20 feet.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1146, 'Camouflage', 'Gripplis receive a +4 racial bonus on Stealth checks in marshes and forested areas.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1147, 'Swamp Stride', 'A grippli can move through difficult terrain at its normal speed while within a swamp. Magically altered terrain affects a grippli normally.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1148, '+2 Dexterity, +2 Constitution', 'Hobgoblins are fast and hardy.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1149, 'Goblinoid', 'Hobgoblins are humanoids with the goblinoid subtype.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1150, 'Sneaky', 'Hobgoblins receive a +4 racial bonus on Stealth checks.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1151, '+2 Dexterity, +2 Charisma, -2 Wisdom', 'Ifrits are passionate and quick, but also impetuous and destructive.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1152, 'Spell-Like Ability', 'Ifrits can use Burning Hands 1/day as a spell-like ability (caster level equals the ifrit''s character level).', 2, 'Ability' );
INSERT INTO ability VALUES ( 1153, 'Fire Affinity', 'Ifrit sorcerers with the elemental (fire) bloodline treat their Charisma scores as 2 points higher for the purposes of all sorcerer spells and class abilities. Ifrit spellcasters with the Fire domain use their domain powers and spells at +1 caster level.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1154, 'Energy Resistance', 'Ifrits have fire resistance 5.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1155, '+2 Dexterity, +2 Charisma, -2 Strength', 'Kitsune are agile and companionable, but tend to be physically weak.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1156, 'Kitsune', 'Kitsune are humanoids with the kitsune and shapechanger subtypes.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1157, 'Change Shape', 'A kitsune can assume the appearance of a specific single human form of the same sex. The kitsune always takes this specific form when she uses this ability. A kitsune in human form cannot use her bite attack, but gains a +10 racial bonus on Disguise checks made to appear human. Changing shape is a standard action. This ability otherwise functions as alter self, except that the kitsune does not adjust her ability scores and can remain in this form indefinitely.', 2, 'Ability' );
INSERT INTO ability VALUES ( 1158, 'Agile', 'Kitsune receive a +2 racial bonus on Acrobatics checks.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1159, 'Kitsune Magic', 'Kitsune add 1 to the DCs of any saving throws to resist enchantment spells that they cast. Kitsune with a Charisma score of 11 or higher gain the following spell-like ability: 3/day-dancing lights.', 2, 'Ability' );
INSERT INTO ability VALUES ( 1160, 'Natural Weapons', 'In her natural form, a kitsune has a bite attack that deals 1d4 points of damage.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1161, '+2 Dexterity, -4 Strength, -2 Constitution', 'Kobolds are fast but weak.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1162, 'Reptilian', 'Are humanoids with the reptilian subtype.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1163, 'Armor +1', 'Have a +1 natural armor bonus.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1164, 'Crafty', 'Kobolds gain a +2 racial bonus on Craft (traps), Perception, and Profession (miner) checks. Craft (traps) and Stealth are always class skills for a kobold.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1165, '+2 Dexterity, +2 Constitution, +2 Charisma', 'Merfolk are graceful, hale, and beautiful. ', 0, 'Ability' );
INSERT INTO ability VALUES ( 1166, 'Aquatic', 'Merfolk are aquatic and can breathe water. Their land speed is 5 feet, but their swim speed is 50 feet. They are amphibious, but prefer not to spend long periods out of the water. ', 0, 'Ability' );
INSERT INTO ability VALUES ( 1167, 'Armor +2', 'Have a +2 natural armor bonus.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1168, '+2 Strength, +2 Charisma, -2 Intelligence', 'Nagaji are strong and have forceful personalities, but they tend to ignore logic and mock scholarly pursuits.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1169, 'Resistant', 'Nagaji receive a +2 racial saving throw bonus against mind-affecting effects and poison.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1170, 'Serpent’s Sense', 'Nagaji receive a +2 racial bonus on Handle Animal checks against reptiles, and a +2 racial bonus on Perception checks.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1171, '+4 Strength, -2 Intelligence, -2 Wisdom, -2 Charisma', 'Orcs are brutal and savage.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1172, 'Orc', 'Orcs are humanoids with the orc subtype', 0, 'Ability' );
INSERT INTO ability VALUES ( 1173, 'Normal Speed', 'Orcs have a base speed of 30 feet.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1174, 'Light Sensitivity', 'Orcs are dazzled in areas of bright sunlight or within the radius of a daylight spell.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1175, 'Ferocity', 'Orcs can remain conscious and continue fighting even if their hit point totals fall below 0. Orcs are still staggered at 0 hit points or lower and lose 1 hit point each round as normal.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1176, '+2 Strength, +2 Wisdom, -2 Charisma', 'Oreads are strong, solid, stable, and stoic.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1177, 'Native Outsider', 'Oreads are outsiders with the native subtype.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1178, 'Slow Speed', 'Oreads have a base speed of 20 feet.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1179, 'Spell-Like Ability', 'Oreads can use magic stone 1/day as spell-like ability (with a caster level equal to the oread''s character level).', 2, 'Ability' );
INSERT INTO ability VALUES ( 1180, 'Energy Resistance', 'Oreads have acid resistance 5.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1181, 'Earth Affinity', 'Oread sorcerers with the elemental (earth) bloodline treat their Charisma scores as 2 points higher for the purposes of all sorcerer spells and class abilities. Oread clerics with the Earth domain use their domain powers and spells at +1 caster level.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1182, '+2 Dexterity, +2 Intelligence, -2 Strength', 'Ratfolk are agile and clever, yet physically weak.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1183, 'Ratfolk', 'Ratfolk are humanoids with the ratfolk subtype.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1184, 'Slow Speed', 'Ratfolk have a base speed of 20 feet.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1185, 'Rodent Empathy', 'Ratfolk gain a +4 racial bonus on Handle Animal checks made to influence rodents.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1186, 'Swarming', 'Ratfolk are used to living and fighting communally, and are adept at swarming foes for their own gain and their foes'' detriment. Up to two ratfolk can share the same square at the same time. If two ratfolk in the same square attack the same foe, they are considered to be flanking that foe as if they were in two opposite squares.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1187, 'Tinker', 'Ratfolk gain a +2 racial bonus on Craft (alchemy), Perception, and Use Magic Device checks.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1188, '+2 Intelligence, +2 Wisdom, -2 Constitution', 'Samsarans are insightful and strong-minded, but with frail bodies.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1189, 'Samsaran', 'Samsarans are humanoids with the samsaran subtype.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1190, 'Lifebound', 'Samsarans gain a +2 racial bonus on all saving throws to resist death effects, saving throws against negative energy effects, Fortitude saves to remove negative levels, and Constitution checks to stabilize if reduced to negative hit points.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1191, 'Samsaran Magic', 'Samsarans with a Charisma score of 11 or higher gain the following spell-like abilities: 1/day- comprehend languages, deathwatch, and stabilize. The caster level for these effects equals the samsaran''s character level.', 2, 'Ability' );
INSERT INTO ability VALUES ( 1192, 'Shards of the Past:', 'A samsaran''s past lives grant her bonuses on two skills. The samsaran chooses two skills-she gains a +2 racial bonus on both, and they are always class skills for her. Once made, this choice can''t be altered.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1193, '+2 Dexterity, -2 Charisma', 'Strix are swift and elusive, but tend to be stubborn and swift to anger.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1194, 'Flight', 'Strix have a fly speed of 60 feet (average).', 0, 'Ability' );
INSERT INTO ability VALUES ( 1195, ' Hatred Strix', 'Strix receive a +1 bonus on attack rolls against humanoid creatures of the human subtype because of their special training against these hated foes.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1196, 'Nocturnal', 'Strix gain a +2 racial bonus on Perception and Stealth checks in dim light or darkness.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1197, 'Suspicious', 'Strix receive a +2 racial bonus on saving throws against illusion spells or effects.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1198, '+2 Strength, +2 Charisma, -2 Intelligence', 'Sulis are brawny and charming, but slow-witted.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1199, 'Negotiator', 'Sulis are keen negotiators, and gain a +2 racial bonus on Diplomacy and Sense Motive checks.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1200, 'Elemental Assault', 'Once per day as a swift action, a suli can shroud her arms in acid, cold, electricity, or fire. This effect lasts for 1 round per level and can be dismissed as a free action. Unarmed strikes with her arms or hands (or attacks with weapons held in those hands) deal +1d6 points of damage of the appropriate energy type.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1201, 'Energy Resistances', 'Sulis have resistance to acid 5, cold 5, electricity 5, and fire 5.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1202, '+2 Dexterity, +2 Wisdom, -2 Strength, -4 Charisma', 'Svirfneblin are fast and observant but relatively weak and emotionally distant.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1203, 'Gnome', 'Svirfneblin are humanoids with the gnome subtype.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1204, 'Slow Speed', 'Race has a base speed of 20 feet.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1205, 'Defensive Training', 'Svirfneblin gain a +2 dodge bonus to their AC.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1206, 'Fortunate', 'Svirfneblin gain a +2 racial bonus on all saving throws', 0, 'Ability' );
INSERT INTO ability VALUES ( 1207, 'Skilled', 'Svirfneblin gain a +2 racial bonus on Stealth checks, this improves to a +4 bonus underground. They gain a +2 racial bonus on Craft (alchemy) checks and Perception checks.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1208, 'Hatred', 'Svirfneblin receive a +1 bonus on attack rolls against humanoid creatures of the reptilian and dwarven subtypes due to training against these hated foes.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1209, 'Stonecunning', 'Svirfneblin gain the stonecunning trait as dwarves.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1210, 'Spell Resistance', 'A svirfneblin has an amount of spell resistance equal to 11 + his character level.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1211, 'Svirfneblin Magic', 'Svirfneblin add 1 to the DCs of any saving throws to resist illusion spells they cast. Svirfneblin also gain the following spell-like abilities: constant-nondetection, 1/day-blindness/deafness, blur, disguise self, caster level equals the svirfneblin''s character level.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1212, '+2 Dexterity, +2 Intelligence, -2 Constitution', 'Sylphs are quick and insightful, but slight and delicate.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1213, 'Spell-Like Ability', 'Sylphs can use feather fall 1/day as a spell-like ability (with a caster level equal to the sylph''s character level).', 2, 'Ability' );
INSERT INTO ability VALUES ( 1214, 'Energy Resistance', 'Sylphs have electricity resistance 5.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1215, 'Air Affinity', 'Sylph sorcerers with the elemental (air) bloodline treat their Charisma scores as 2 points higher for the purposes of all sorcerer spells and class abilities. Sylph spellcasters with the Air domain use their domain powers and spells at +1 caster level.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1216, '+2 Dexterity, +2 Wisdom, -2 Constitution', 'Tengus are fast and observant, but relatively fragile.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1217, 'Tengu', 'Tengus are humanoids with the tengu subtype.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1218, 'Sneaky', 'Tengus gain a +2 racial bonus on Perception and Stealth checks.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1219, 'Gifted Linguist', 'Tengus gain a +4 racial bonus on Linguistics checks, and learn two languages each time they gain a rank in Linguistics rather than one language.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1220, 'Swordtrained', 'Tengus are automatically proficient with swordlike weapons (including bastard swords, daggers, elven curve blades, falchions, greatswords, kukris, longswords, punching daggers, rapiers, scimitars, short swords, and two-bladed swords).', 0, 'Ability' );
INSERT INTO ability VALUES ( 1221, 'Natural Weapon', 'A tengu has a bite attack that deals 1d3 points of damage.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1222, '+2 Dexterity, +2 Intelligence, -2 Charisma', 'Tieflings are quick in body and mind, but are inherently unnerving. Tieflings of specific bloodlines (see below) gain different ability score modifiers as indicated.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1223, 'Skilled', 'Tieflings gain a +2 racial bonus on Bluff and Stealth checks. Tieflings of specific bloodlines (see below) gain a +2 bonus on different skill checks as indicated.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1224, 'Spell-Like Ability', 'Tieflings can use darkness once per day as a spell-like ability (with a caster level equal to the tiefling''s character level). Tieflings of specific bloodlines (see below) gain different spell-like abilities.', 2, 'Ability' );
INSERT INTO ability VALUES ( 1225, 'Fiendish Resistance', 'Tieflings have cold resistance 5, electricity resistance 5, and fire resistance 5.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1226, 'Fiendish Sorcery', 'Tiefling sorcerers with the Abyssal or Infernal bloodlines treat their Charisma scores as 2 points higher for the purposes of all sorcerer class abilities.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1227, '+2 Dexterity, +2 Wisdom, -2 Strength', 'Undines are perceptive and agile, but somewhat weak.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1228, 'Spell-Like Ability', 'Undines can cast hydraulic push once per day as a spell-like ability (with a caster level equal to the undine''s character level).', 2, 'Ability' );
INSERT INTO ability VALUES ( 1229, 'Energy Resistance', 'Undines have cold resistance 5.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1230, 'Water Affinity', 'Undine sorcerers with the elemental (water) bloodline treat their Charisma scores as 2 points higher for the purposes of all sorcerer spells and class abilities. Undine clerics with the Water domain cast their Water domain powers and spells at +1 caster level.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1231, '+2 Dexterity, +2 Wisdom, -2 Charisma:', 'Vanaras are agile and perceptive, but are also rather impish and mischievous.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1232, 'Vanara', 'Vanaras are humanoids with the vanara subtype.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1233, 'Nimble', 'Vanaras have a +2 racial bonus on Acrobatics and Stealth checks.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1234, 'Climb speed', 'Vanaras have a base speed of 30 feet and a Climb speed of 20 feet.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1235, 'Prehensile Tail', 'A vanara has a long, flexible tail that she can use to carry objects. She cannot wield weapons with her tail, but the tail allows her to retrieve a small, stowed object carried on her person as a swift action.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1236, '+2 Dexterity, +2 Charisma, -2 Wisdom', 'Vishkanyas are graceful but often irrational.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1237, 'Vishkanya', 'Vishkanyas are humanoids with the vishkanya subtype.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1238, 'Poison Resistance', 'A vishkanya has a racial bonus on saving throws against poison equal to its Hit Dice.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1239, 'Limber', 'Vishkanyas receive a +2 racial bonus on Escape Artist and Stealth checks.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1240, 'Toxic', 'A number of times per day equal to his Constitution modifier (minimum 1/day), a vishkanya can envenom a weapon that he wields with his toxic saliva or blood (using blood requires the vishkanya to be injured when he uses this ability). Applying venom in this way is a swift action. Vishkanya Venom: Weapon-injury, save Fort DC 10 + 1/2 the vishkanya''s Hit Dice + the vishkanya''s Constitution modifier, frequency 1/round for 6 rounds, effect 1d2 Dex, cure 1 save.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1241, 'Weapon Familiarity', 'Vishkanyas are always proficient with blowguns, kukri, and shuriken.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1242, '+2 Dexterity, +2 Intelligence, -2 Wisdom', 'Wayangs are nimble and cagey, but their perception of the world is clouded by shadows.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1243, 'Wayang', 'Wayangs are humanoids with the wayang subtype.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1244, 'Light and Dark', 'Once per day as an immediate action, a wayang can treat positive and negative energy effects as if she were an undead creature, taking damage from positive energy and being healed of damage by negative energy. This ability lasts for 1 minute once activated.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1245, 'Lurker', 'Wayangs gain a +2 racial bonus on Perception and Stealth checks.', 0, 'Ability' );
INSERT INTO ability VALUES ( 1246, 'Shadow Magic', 'Wayangs add 1 to the DC of any saving throws to resist spells of the shadow subschool that they cast. Wayangs with a Charisma score of 11 or higher also gain the following spell-like abilities: 1/day-ghost sound, pass without trace, and ventriloquism. The caster level for these effects is equal to the wayang''s character level. The DCs of these spells are equal to 10 + the spell''s level + the wayang''s Charisma modifier.', 2, 'Ability' );
INSERT INTO ability VALUES ( 1247, 'Shadow Resistance', 'Wayangs get a +2 racial bonus on saving throws against spells of the shadow subschool.', 0, 'Ability' );


INSERT INTO race_ability VALUES (11, 1084);
INSERT INTO race_ability VALUES (11, 1085);
INSERT INTO race_ability VALUES (11, 1086);
INSERT INTO race_ability VALUES (11, 1087);
INSERT INTO race_ability VALUES (11, 1088);
INSERT INTO race_ability VALUES (11, 2);
INSERT INTO race_ability VALUES (12, 1089);
INSERT INTO race_ability VALUES (12, 1090);
INSERT INTO race_ability VALUES (12, 1091);
INSERT INTO race_ability VALUES (12, 1092);
INSERT INTO race_ability VALUES (12, 9);
INSERT INTO race_ability VALUES (12, 1093);
INSERT INTO race_ability VALUES (13, 1094);
INSERT INTO race_ability VALUES (13, 1095);
INSERT INTO race_ability VALUES (13, 1096);
INSERT INTO race_ability VALUES (13, 1097);
INSERT INTO race_ability VALUES (13, 1098);
INSERT INTO race_ability VALUES (13, 1099);
INSERT INTO race_ability VALUES (13, 1100);
INSERT INTO race_ability VALUES (13, 1101);
INSERT INTO race_ability VALUES (13, 1102);
INSERT INTO race_ability VALUES (13, 1103);
INSERT INTO race_ability VALUES (13, 1104);
INSERT INTO race_ability VALUES (13, 1105);
INSERT INTO race_ability VALUES (13, 2);
INSERT INTO race_ability VALUES (14, 1106);
INSERT INTO race_ability VALUES (14, 1107);
INSERT INTO race_ability VALUES (14, 1108);
INSERT INTO race_ability VALUES (14, 1109);
INSERT INTO race_ability VALUES (14, 1110);
INSERT INTO race_ability VALUES (14, 1111);
INSERT INTO race_ability VALUES (14, 1112);
INSERT INTO race_ability VALUES (14, 1113);
INSERT INTO race_ability VALUES (15, 1114);
INSERT INTO race_ability VALUES (15, 1116);
INSERT INTO race_ability VALUES (15, 1117);
INSERT INTO race_ability VALUES (15, 1118);
INSERT INTO race_ability VALUES (15, 1119);
INSERT INTO race_ability VALUES (15, 1120);
INSERT INTO race_ability VALUES (15, 1121);
INSERT INTO race_ability VALUES (16, 1122);
INSERT INTO race_ability VALUES (16, 1123);
INSERT INTO race_ability VALUES (16, 1124);
INSERT INTO race_ability VALUES (16, 1125);
INSERT INTO race_ability VALUES (16, 1121);
INSERT INTO race_ability VALUES (16, 7);
INSERT INTO race_ability VALUES (17, 1085);
INSERT INTO race_ability VALUES (17, 2);
INSERT INTO race_ability VALUES (17, 9);
INSERT INTO race_ability VALUES (17, 1126);
INSERT INTO race_ability VALUES (17, 1127);
INSERT INTO race_ability VALUES (17, 1128);
INSERT INTO race_ability VALUES (17, 1129);
INSERT INTO race_ability VALUES (17, 1130);
INSERT INTO race_ability VALUES (18, 1131);
INSERT INTO race_ability VALUES (18, 1132);
INSERT INTO race_ability VALUES (18, 1133);
INSERT INTO race_ability VALUES (18, 1134);
INSERT INTO race_ability VALUES (18, 1135);
INSERT INTO race_ability VALUES (18, 1136);
INSERT INTO race_ability VALUES (19, 2);
INSERT INTO race_ability VALUES (19, 1137);
INSERT INTO race_ability VALUES (19, 1138);
INSERT INTO race_ability VALUES (19, 1139);
INSERT INTO race_ability VALUES (19, 1140);
INSERT INTO race_ability VALUES (19, 1141);
INSERT INTO race_ability VALUES (20, 2);
INSERT INTO race_ability VALUES (20, 1142);
INSERT INTO race_ability VALUES (20, 1139);
INSERT INTO race_ability VALUES (20, 1143);
INSERT INTO race_ability VALUES (20, 1144);
INSERT INTO race_ability VALUES (20, 1145);
INSERT INTO race_ability VALUES (20, 1146);
INSERT INTO race_ability VALUES (20, 1147);
INSERT INTO race_ability VALUES (21, 1148);
INSERT INTO race_ability VALUES (21, 1149);
INSERT INTO race_ability VALUES (21, 1150);
INSERT INTO race_ability VALUES (21, 2);
INSERT INTO race_ability VALUES (22, 1085);
INSERT INTO race_ability VALUES (22, 2);
INSERT INTO race_ability VALUES (22, 1151);
INSERT INTO race_ability VALUES (22, 1152);
INSERT INTO race_ability VALUES (22, 1153);
INSERT INTO race_ability VALUES (22, 1154);
INSERT INTO race_ability VALUES (23, 1155);
INSERT INTO race_ability VALUES (23, 1156);
INSERT INTO race_ability VALUES (23, 1157);
INSERT INTO race_ability VALUES (23, 1158);
INSERT INTO race_ability VALUES (23, 1159);
INSERT INTO race_ability VALUES (23, 9);
INSERT INTO race_ability VALUES (23, 1160);
INSERT INTO race_ability VALUES (24, 1161);
INSERT INTO race_ability VALUES (24, 1162);
INSERT INTO race_ability VALUES (24, 1139);
INSERT INTO race_ability VALUES (24, 2);
INSERT INTO race_ability VALUES (24, 1163);
INSERT INTO race_ability VALUES (24, 1164);
INSERT INTO race_ability VALUES (24, 1125);
INSERT INTO race_ability VALUES (25, 1165);
INSERT INTO race_ability VALUES (25, 1166);
INSERT INTO race_ability VALUES (25, 1167);
INSERT INTO race_ability VALUES (25, 9);
INSERT INTO race_ability VALUES (26, 1168);
INSERT INTO race_ability VALUES (26, 1169);
INSERT INTO race_ability VALUES (26, 1170);
INSERT INTO race_ability VALUES (26, 9);
INSERT INTO race_ability VALUES (26, 1162);
INSERT INTO race_ability VALUES (26, 1163);
INSERT INTO race_ability VALUES (27, 2);
INSERT INTO race_ability VALUES (27, 1171);
INSERT INTO race_ability VALUES (27, 1172);
INSERT INTO race_ability VALUES (27, 1173);
INSERT INTO race_ability VALUES (27, 1174);
INSERT INTO race_ability VALUES (27, 1175);
INSERT INTO race_ability VALUES (28, 2);
INSERT INTO race_ability VALUES (28, 1176);
INSERT INTO race_ability VALUES (28, 1177);
INSERT INTO race_ability VALUES (28, 1178);
INSERT INTO race_ability VALUES (28, 1179);
INSERT INTO race_ability VALUES (28, 1180);
INSERT INTO race_ability VALUES (28, 1181);
INSERT INTO race_ability VALUES (29, 2);
INSERT INTO race_ability VALUES (29, 1182);
INSERT INTO race_ability VALUES (29, 1183);
INSERT INTO race_ability VALUES (29, 1139);
INSERT INTO race_ability VALUES (29, 1184);
INSERT INTO race_ability VALUES (29, 1185);
INSERT INTO race_ability VALUES (29, 1186);
INSERT INTO race_ability VALUES (29, 1187);
INSERT INTO race_ability VALUES (30, 9);
INSERT INTO race_ability VALUES (30, 1188);
INSERT INTO race_ability VALUES (30, 1189);
INSERT INTO race_ability VALUES (30, 1190);
INSERT INTO race_ability VALUES (30, 1191);
INSERT INTO race_ability VALUES (30, 1192);
INSERT INTO race_ability VALUES (31, 2);
INSERT INTO race_ability VALUES (31, 9);
INSERT INTO race_ability VALUES (31, 1193);
INSERT INTO race_ability VALUES (31, 1194);
INSERT INTO race_ability VALUES (31, 1195);
INSERT INTO race_ability VALUES (31, 1196);
INSERT INTO race_ability VALUES (31, 1197);
INSERT INTO race_ability VALUES (32, 9);
INSERT INTO race_ability VALUES (32, 1085);
INSERT INTO race_ability VALUES (32, 1204);
INSERT INTO race_ability VALUES (32, 1205);
INSERT INTO race_ability VALUES (32, 1206);
INSERT INTO race_ability VALUES (32, 1207);
INSERT INTO race_ability VALUES (33, 1139);
INSERT INTO race_ability VALUES (33, 1121);
INSERT INTO race_ability VALUES (33, 1202);
INSERT INTO race_ability VALUES (33, 1203);
INSERT INTO race_ability VALUES (33, 1204);
INSERT INTO race_ability VALUES (33, 1205);
INSERT INTO race_ability VALUES (33, 1206);
INSERT INTO race_ability VALUES (33, 1207);
INSERT INTO race_ability VALUES (33, 1208);
INSERT INTO race_ability VALUES (33, 1209);
INSERT INTO race_ability VALUES (33, 1210);
INSERT INTO race_ability VALUES (33, 1211);
INSERT INTO race_ability VALUES (34, 1085);
INSERT INTO race_ability VALUES (34, 2);
INSERT INTO race_ability VALUES (34, 1218);
INSERT INTO race_ability VALUES (34, 1219);
INSERT INTO race_ability VALUES (34, 1220);
INSERT INTO race_ability VALUES (34, 1221);
INSERT INTO race_ability VALUES (35, 9);
INSERT INTO race_ability VALUES (35, 1215);
INSERT INTO race_ability VALUES (35, 1216);
INSERT INTO race_ability VALUES (35, 1217);
INSERT INTO race_ability VALUES (35, 1218);
INSERT INTO race_ability VALUES (35, 1219);
INSERT INTO race_ability VALUES (35, 1220);
INSERT INTO race_ability VALUES (35, 1221);
INSERT INTO race_ability VALUES (36, 1085);
INSERT INTO race_ability VALUES (36, 2);
INSERT INTO race_ability VALUES (36, 1222);
INSERT INTO race_ability VALUES (36, 1223);
INSERT INTO race_ability VALUES (36, 1224);
INSERT INTO race_ability VALUES (36, 1225);
INSERT INTO race_ability VALUES (36, 1226);
INSERT INTO race_ability VALUES (37, 1085);
INSERT INTO race_ability VALUES (37, 2);
INSERT INTO race_ability VALUES (37, 1227);
INSERT INTO race_ability VALUES (37, 1228);
INSERT INTO race_ability VALUES (37, 1229);
INSERT INTO race_ability VALUES (37, 1230);
INSERT INTO race_ability VALUES (38, 9);
INSERT INTO race_ability VALUES (38, 1231);
INSERT INTO race_ability VALUES (38, 1232);
INSERT INTO race_ability VALUES (38, 1233);
INSERT INTO race_ability VALUES (38, 1234);
INSERT INTO race_ability VALUES (38, 1235);
INSERT INTO race_ability VALUES (39, 9);
INSERT INTO race_ability VALUES (39, 12);
INSERT INTO race_ability VALUES (39, 1116);
INSERT INTO race_ability VALUES (39, 1236);
INSERT INTO race_ability VALUES (39, 1237);
INSERT INTO race_ability VALUES (39, 1238);
INSERT INTO race_ability VALUES (39, 1239);
INSERT INTO race_ability VALUES (39, 1240);
INSERT INTO race_ability VALUES (39, 1241);
INSERT INTO race_ability VALUES (40, 1139);
INSERT INTO race_ability VALUES (40, 2);
INSERT INTO race_ability VALUES (40, 1204);
INSERT INTO race_ability VALUES (40, 1242);
INSERT INTO race_ability VALUES (40, 1243);
INSERT INTO race_ability VALUES (40, 1244);
INSERT INTO race_ability VALUES (40, 1245);
INSERT INTO race_ability VALUES (40, 1246);
INSERT INTO race_ability VALUES (40, 1247);
